[package]
name = "airlang_bin"
version = "0.23.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Air is a minimalist and universal programming language."
repository = "https://github.com/LambdaAlpha/airlang_rs"
keywords = ["programming-language", "dsl", "config", "configuration", "serde"]
categories = ["compilers"]

[lints]
workspace = true

[dependencies.airlang]
path = "../lib"
version = "0.23.0"

[dependencies.airlang_ext]
path = "../ext"
version = "0.23.0"

# repl
[dependencies.crossterm]
version = "0.29"

# const str
[dependencies.const_format]
version = "0.2"

# log
[dependencies.log]
version = "0.4"
default-features = false
features = ["release_max_level_off"]

# log
[dev-dependencies.airlang_dev]
path = "../dev"
