style_edition = "2024"
edition = "2021"
unstable_features = true
imports_granularity = "Crate"
imports_layout = "Vertical"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = false
reorder_impl_items = false
use_field_init_shorthand = true
overflow_delimited_expr = true
hex_literal_case = "Lower"
format_code_in_doc_comments = true
