edition = "2024"
style_edition = "2024"
unstable_features = true

format_generated_files = false
format_macro_matchers = true
format_code_in_doc_comments = true

newline_style = "Unix"

imports_granularity = "Item"
group_imports = "StdExternalCrate"
reorder_imports = true

reorder_modules = false
reorder_impl_items = false

use_small_heuristics = "Max"
fn_params_layout = "Compressed"

brace_style = "PreferSameLine"
overflow_delimited_expr = true
where_single_line = true

use_field_init_shorthand = true

spaces_around_ranges = true

hex_literal_case = "Lower"
